# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: catalog-service

replicaCount: 3

image:
  repository: arahna/catalog-service
  pullPolicy: IfNotPresent
  tag: v1.0

migrationsimage:
  repository: arahna/catalog-service-migrations
  pullPolicy: IfNotPresent
  tag: v1.0

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: app
  postgresqlPassword: apppwd
  postgresqlDatabase: catalog
  service:
    port: "5432"
  metrics:
    enabled: true
    service:
      type: NodePort
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    serviceMonitor:
      enabled: true
      additionalLabels: {}
      interval: 30s
      scrapeTimeout: 10s
    config:
      datasourceSecret:
        name: catalog-service-secret
        key: DB_URI

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/catalog$1$2
  hosts:
    - host: arch.homework
      paths: [/api/v1/catalog($|/)(.*)]

metrics:
  serviceMonitor:
    enabled: true